FROM node:16-alpine AS build
RUN mkdir -p /app/client
WORKDIR /app/client

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/client/node_modules/.bin:$PATH

# COPY ./public ./public
# COPY ./src ./src
COPY . .

# install app dependencies
COPY package.json ./
RUN yarn install --silent
RUN yarn run build
# CMD ["npm", "build"]

FROM nginx:1.23


COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/client/build /usr/share/nginx/html

# EXPOSE 3000
# CMD ["npm", "start","--legacy-peer-deps"]